---
config:
  backup_password: '<PASSWORD>'

  # global config. Note: currently some other keys are used as global conf
  global_secret_key: '<PASSWORD>'
  cloudflare: True

  # election-orchestra
  port: 5000
  host: agora-auth5
  public_ipaddress: 192.168.0.11
  private_ipaddress: 192.168.0.11
  vfork_server_ports: [4081, 4083]
  vfork_hint_server_ports: [8081, 8083]
  auto_mode: true

  # agora-elections
  agora_elections_db_password: '<PASSWORD>'
  agora_elections_shared_secret: '<PASSWORD>'
  agora_elections_expiry: 60000
  agora_elections_domain: dev.agoravoting.com
  agora_elections_port: 14443
  keystore_pass: supersecret

  # agora-gui
  agora_gui_domain: dev.agoravoting.com
  agora_gui_admin_port: 10090
  agora_gui_booth_port: 10091
  agora_gui_elections_port: 10092
  agora_gui_lang: es

  # dnie config
  dnie_host: cert.agora-auth5

  cert:
    C: ES
    ST: Madrid
    L: Madrid
    O: Agoravoting
    OU: Agora_Voting_SL
    EMAIL: agora@agoravoting.com

  # sentry
  sentry_port: 9090
  sentry_db_password: '<PASSWORD>'
  sentry_admin_password: '<PASSWORD>'

  # Authorities

  authorities:
    - id: "auth1"
      name: "Agora Voting"
      description: "Agora Voting es un software libre de votaciones que permite a cualquier organización realizar procesos electorales de forma segura, flexible, transparente y a un precio competitivo."
      url: "https://agoravoting.com"
      image: "/docs/logo_agora.png"
    - id: "auth2"
      name: "Agora Voting 1"
      description: "Agora Voting es un software libre de votaciones que permite a cualquier organización realizar procesos electorales de forma segura, flexible, transparente y a un precio competitivo."
      url: "https://agoravoting.com"
      image: "/docs/logo_agora.png"
  director: 'auth1'
  auths: "['auth2']"
