---
config:
  backup_password: '<PASSWORD>'

  # global config. Note: currently some other keys are used as global conf
  global_secret_key: '<PASSWORD>'
  cloudflare: True

  # election-orchestra
  port: 5000
  host: agora-auth5
  public_ipaddress: 192.168.0.11
  private_ipaddress: 192.168.0.11
  vfork_server_ports: [4081, 4083]
  vfork_hint_server_ports: [8081, 8083]
  auto_mode: true

  # agora-elections
  agora_elections_db_password: '<PASSWORD>'
  agora_elections_shared_secret: '<PASSWORD>'
  agora_elections_expiry: 60000
  agora_elections_domain: dev.agoravoting.com
  agora_elections_port: 14443
  keystore_pass: supersecret

  # agora-core-view
  agora_core_view_domain: dev.agoravoting.com
  agora_core_view_port: 14444

  # dnie config
  dnie_host: cert.agora-auth5

  cert:
    C: ES
    ST: Madrid
    L: Madrid
    O: Agoravoting
    OU: Agora_Voting_SL
    EMAIL: agora@agoravoting.com

  # sentry
  sentry_port: 9090
  sentry_db_password: '<PASSWORD>'
  sentry_admin_password: '<PASSWORD>'
