---
config:
  backup_password: '<PASSWORD>'

  # election-orchestra
  port: 5000
  host: agora-auth5
  public_ipaddress: 192.168.0.11
  private_ipaddress: 192.168.0.11
  verificatum_server_ports: [4081, 4083]
  verificatum_hint_server_ports: [8081, 8083]
  auto_mode: true

  # agora-elections
  agora_elections_db_password: '<PASSWORD>'
  agora_elections_shared_secret: '<PASSWORD>'
  agora_elections_expiry: 60000
  agora_elections_domain: dev.agoravoting.com
  agora_elections_port: 14443

  # agora-core-view
  agora_core_view_domain: dev.agoravoting.com
  agora_core_view_port: 14444
