---
- name: AgoraVerifier, check if avConfig.js exists
  stat: path=/home/agoragui/avConfig.js
  register: avConfig

- name: AgoraVerifier, get hash of verifier
  shell: sha256sum /home/agoraverifier/agora-verifier | cut -d' ' -f 1
  register: sha256sum

- name: AgoraVerifier, config setup for agora-verifier
  sudo: true
  sudo_user: agoragui
  when: avConfig.stat.exists == True
  replace:
    dest: /home/agoragui/avConfig.js
    regexp: "{{item.regexp}}"
    replace: "{{item.replace}}"
  with_items:
    - regexp: "link:.*"
      replace: 'link: "https://{{config.agora_elections.domain}}/verifier/agora-verifier",'

    - regexp: "hash:.*"
      replace: 'hash: "{{sha256sum.stdout}}",'

- name: AgoraVerifier, building AgoraGui
  sudo: true
  sudo_user: agoragui
  when: avConfig.stat.exists == True
  shell: ./build.sh chdir=/home/agoragui/
