---
config:
  backup_password: 'secret-agora-backup'

  # global config. Note: currently some other keys are used as global conf
  global_secret_key: 'SECRET-KEY'

  # election-orchestra
  port: 5000
  host: agora
  public_ipaddress: 192.168.50.4
  private_ipaddress: 192.168.50.4
  vfork_server_ports: [4081, 4083]
  vfork_hint_server_ports: [8081, 8083]
  auto_mode: true

  # agora-elections
  agora_elections_db_password: 'agora_elections'
  agora_elections_shared_secret: 'SHARED'
  agora_elections_expiry: 60000
  agora_elections_domain: agora
  agora_elections_port: 14443
  keystore_pass: supersecret

  # agora-core-view
  agora_core_view_domain: agora
  agora_core_view_port: 14444

  cert:
    C: ES
    ST: Sevilla
    L: Sevilla
    O: Wadobo
    OU: Wadobo
    EMAIL: info@wadobo.com

  # sentry
  sentry_port: 9090
  sentry_db_password: 'secret-password'
  sentry_admin_password: 'secret-password'
