---
config:
  backup_password: 'secret-agora-backup'

  # global config. Note: currently some other keys are used as global conf
  global_secret_key: 'SECRET-KEY'
  cloudflare: True

  # election-orchestra
  port: 5000
  host: agora
  public_ipaddress: 192.168.50.4
  private_ipaddress: 192.168.50.4
  vfork_server_ports: [4081, 4083]
  vfork_hint_server_ports: [8081, 8083]
  auto_mode: true

  # agora-elections
  agora_elections_db_password: 'agora_elections'
  agora_elections_shared_secret: 'SHARED'
  agora_elections_expiry: 60000
  agora_elections_domain: agora
  agora_elections_port: 14443
  keystore_pass: supersecret

  # agora-core-view
  agora_core_view_domain: agora
  agora_core_view_port: 14444

  # dnie config
  dnie_host: cert.agora-auth5

  cert:
    C: ES
    ST: Sevilla
    L: Sevilla
    O: Wadobo
    OU: Wadobo
    EMAIL: info@wadobo.com

  # sentry
  sentry_port: 9090
  sentry_db_password: 'secret-password'
  sentry_admin_password: 'secret-password'

  # Authorities

  authorities:
    - id: "local-auth1"
      name: "Agora Voting 1"
      description: "Agora Voting es un software libre de votaciones que permite a cualquier organización realizar procesos electorales de forma segura, flexible, transparente y a un precio competitivo."
      url: "https://agoravoting.com"
      image: "/docs/logo_agora.png"
    - id: "local-auth2"
      name: "Agora Voting 2"
      description: "Agora Voting es un software libre de votaciones que permite a cualquier organización realizar procesos electorales de forma segura, flexible, transparente y a un precio competitivo."
      url: "https://agoravoting.com"
      image: "/docs/logo_agora.png"
  director: 'local-auth1'
  auths: "['local-auth2']"
