---
params:
  sleep:
    fast: 2
    slow: 6

config:
  backup_password: 'secret-auth2-backup'

  # global config. Note: currently some other keys are used as global conf
  global_secret_key: 'SECRET-KEY'

  # election-orchestra
  port: 5000
  host: local-auth2
  public_ipaddress: 192.168.50.3
  private_ipaddress: 192.168.50.3
  vfork_server_ports: [4081, 4083]
  vfork_hint_server_ports: [8081, 8083]
  auto_mode: true

  # agora-elections
  agora_elections_db_password: '<PASSWORD>'
  agora_elections_shared_secret: '<PASSWORD>'
  agora_elections_expiry: 60000
  agora_elections_domain: agora.dev
  agora_elections_port: 14443
  keystore_pass: supersecret

  # agora-gui
  agora_gui_domain: agora
  agora_gui_admin_port: 10090
  agora_gui_booth_port: 10091
  agora_gui_elections_port: 10092
  agora_gui_lang: es

  cert:
    C: ES
    ST: Sevilla
    L: Sevilla
    O: Wadobo
    OU: Wadobo
    EMAIL: info@wadobo.com
