# This file is part of agora-dev-box.
# Copyright (C) 2014-2016  Agora Voting SL <agora@agoravoting.com>

# agora-dev-box is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License.

# agora-dev-box  is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with agora-dev-box.  If not, see <http://www.gnu.org/licenses/>.

---
- hosts: all

  tasks:
    - include_vars: config.yml
    - include_vars: repos.yml

    - import_tasks: packages.yml
    - import_tasks: system.yml
    - import_tasks: hardening/main.yml
    - import_tasks: sudoers/main.yml
    - import_tasks: agora-tools/main.yml
    - import_tasks: eorchestra/main.yml
    #- import_tasks: agora-elections/main.yml
    #- import_tasks: authapi/main.yml
    #- import_tasks: sentry/main.yml
    #- import_tasks: agora-gui/main.yml
    #- import_tasks: oneserver/main.yml
    - import_tasks: agora-verifier/main.yml
    #- import_tasks: halb/main.yml
    - import_tasks: postgres_backups.yml
    #- import_tasks: crontab.yml
